services:

    _defaults:
        public: false
        autowire: true

    Marmalade\GraphQL\GraphQLPlayground\:
        resource: 'src/*'
        exclude: 'src/**/DataType'
        public: true

    Marmalade\GraphQL\GraphQLPlayground\Shared\Service\NamespaceMapper:
        class: Marmalade\GraphQL\GraphQLPlayground\Shared\Service\NamespaceMapper
        tags: ['graphql_namespace_mapper']
