services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\Storefront\:
    resource: 'src/*'
    exclude: 'src/**/{DataType,Exception,Shop}'
    public: true

  OxidEsales\GraphQL\Storefront\Shared\Service\NamespaceMapper:
      class: OxidEsales\GraphQL\Storefront\Shared\Service\NamespaceMapper
      tags: ['graphql_namespace_mapper']

  OxidEsales\GraphQL\Storefront\Shared\Service\PermissionProvider:
      class: OxidEsales\GraphQL\Storefront\Shared\Service\PermissionProvider
      tags: ['graphql_permission_provider']
